# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "ORDERS" ("ID" SERIAL NOT NULL PRIMARY KEY,"CLIENTNAME" VARCHAR(254) DEFAULT '' NOT NULL,"EMAIL" VARCHAR(254) DEFAULT '' NOT NULL,"ADDRESS" VARCHAR(254) DEFAULT '' NOT NULL,"PRODUCTID" INTEGER DEFAULT 0 NOT NULL,"TIME" VARCHAR(254) DEFAULT '' NOT NULL,"ISDELIVERED" BOOLEAN DEFAULT false NOT NULL);
create table "PRODUCTS" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) DEFAULT '' NOT NULL,"DESCRIPTION" VARCHAR(254) DEFAULT '' NOT NULL,"IMAGE" VARCHAR(254) DEFAULT 'logo.png' NOT NULL,"PRICE" INTEGER DEFAULT 0 NOT NULL);

# --- !Downs

drop table "PRODUCTS";
drop table "ORDERS";

