# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "PRODUCTS" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) DEFAULT '' NOT NULL,"DESCRIPTION" VARCHAR(254) DEFAULT '' NOT NULL,"IMAGE" VARCHAR(254) DEFAULT 'logo.png' NOT NULL,"PRICE" INT NOT NULL);
create table "ORDERS" ("ID" SERIAL NOT NULL PRIMARY KEY,"CLIENTNAME" VARCHAR(254) DEFAULT '' NOT NULL,"EMAIL" VARCHAR(254) DEFAULT '' NOT NULL,"ADRESS" VARCHAR(254) DEFAULT '' NOT NULL,"PRODUCTID" INT NOT NULL,"ISDILEVERED" BOOLEAN NOT NULL DEFAULT FALSE);
# --- !Downs

drop table "PRODUCTS";
drop table "ORDERS";

